###Admin api requests
###admin register
POST http://localhost:4000/admin-api/register
Content-Type: application/json

{
    "username":"admin",
    "password":"admin123"
}

###admin login
POST http://localhost:4000/admin-api/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin123"
}

###add movie
POST http://localhost:4000/admin-api/add-movie
Content-Type: application/json

{
    "movieId":"2",
    "movieName":"Oye"
}

###remove movie
POST http://localhost:4000/admin-api/remove-movie/2


###update movie
POST http://localhost:4000/admin-api/update-movie
Content-Type: application/json

{
    "movieId":"1",
    "movieName":"Billaaaa"
}


###add user
POST http://localhost:4000/admin-api/add-user
Content-Type: application/json

{
    "userId":"1",
    "userName":"Prabhas"
}

###update user
PUT http://localhost:4000/admin-api/update-user
Content-Type: application/json

{
    "userId":"1",
    "userName":"Prabhassss"
}

###remove user
POST http://localhost:4000/admin-api/remove-user/1

### Get Shows 
POST http://localhost:4000/admin-api/get-shows
Content-Type: application/json

{
    "movieId":"1724689844610",
    "date":"25/7/23"
}